name: bo-machine-learning

channels:
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - pandas
  - ipykernel
  - transformers
  - datasets
  - evaluate
  - pip
  - pip:
      - gpt_2_simple
      - sklearn
      - tensorflow
      - tensorflowjs
