version: "3"

services:
  backend:
    build: ./server
    ports:
      - 3000:3000
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: postgres
      DB_SCHEMA: public
      CORS_ENABLE: "true"
      CORS_ORIGINS: "http://localhost:4200"

  frontend:
    build: ./client
    ports:
      - 4200:4200

  ml-runner:
    build: ./ml-runner

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password

  adminer:    
    image: adminer
    ports: 
      - 8080:8080
