import { INestApplication } from "@nestjs/common";
import { GUARDS_METADATA } from "@nestjs/common/constants";
import { DocumentBuilder, OpenAPIObject, SwaggerModule } from "@nestjs/swagger";
import { Request } from "express";
import { RouteStore } from "./access-control/access-control-lib/route-store";
import { UserGuard } from "./auth/guards/user.guard";
import { Config } from "./config";

// uncomment if using SWC compiler
// import metadata from "./metadata";

const ROOT_TAG = "Root" as const;
const PUBLIC_TAG = "Public API" as const;

/** Security scheme name referenced by operations that require an authenticated session. */
const COOKIE_AUTH_SCHEME = "cookieAuth" as const;

/** Name of the httpOnly session cookie set by TokenService — the credential the API authenticates with. */
const SESSION_COOKIE_NAME = "token" as const;

export function generateOpenAPI(path: string, app: INestApplication, config: Config) {
	const builder = new DocumentBuilder()
		.setTitle(config.app.name)
		.setVersion(config.app.version)
		.addServer(config.app.baseUrl)
		.addTag(
			PUBLIC_TAG,
			"Unauthenticated public API consumed by the public bosan.cz website frontend. " +
				"Exposes only published events (program) and published photo galleries, in the " +
				"legacy response shape the website expects (string `_id`s, photo `sizes`, `_links`). " +
				"These endpoints require no login and are safe to call cross-origin from the website.",
		)
		// Authentication is a JWT carried in the httpOnly `token` cookie (see TokenService). The browser
		// attaches it automatically on same-site/credentialed requests; there is no Authorization header.
		.addCookieAuth(
			SESSION_COOKIE_NAME,
			{
				type: "apiKey",
				in: "cookie",
				name: SESSION_COOKIE_NAME,
				description:
					"Session authentication via the httpOnly `token` cookie issued on login. Sent " +
					"automatically by the browser; it cannot be set from JavaScript.",
			},
			COOKIE_AUTH_SCHEME,
		)
		// Apply the session cookie as the default requirement for every operation; genuinely public
		// endpoints opt out below by getting an explicit empty `security`.
		.addSecurityRequirements(COOKIE_AUTH_SCHEME)
		.build();

	// uncomment if using SWC compiler
	// await SwaggerModule.loadPluginMetadata(metadata);

	const document = SwaggerModule.createDocument(app, builder, {
		autoTagControllers: false,
		operationIdFactory: (controllerKey: string, methodKey: string) => methodKey,
	});

	// SwaggerModules does not add the OpenAPI paths for the paths generated by itself, so we need to add them manually
	addOpenapiPaths(path, document);

	// Mark the endpoints reachable without a session as public (overrides the global requirement above)
	markPublicOperations(document);

	return document;
}

export function registerOpenAPI(path: string, app: INestApplication, config: Config) {
	const openapiDocument = generateOpenAPI(path, app, config);

	function openapiTagSorter(a: string, b: string) {
		const rootTag: typeof ROOT_TAG = "Root";
		if (a === rootTag) return -1;
		if (b === rootTag) return 1;
		return a.localeCompare(b);
	}

	SwaggerModule.setup(path, app, openapiDocument, {
		swaggerOptions: {
			tagsSorter: openapiTagSorter,
			operationsSorter: "alpha",
		},
	});
}

/**
 * Add OpenAPI paths to the document
 */
function addOpenapiPaths(prefix: string, document: OpenAPIObject) {
	if (!prefix.startsWith("/")) prefix = "/" + prefix;
	if (prefix.endsWith("/") && prefix !== "/") prefix = prefix.slice(0, -1);

	const paths = {
		[prefix]: {
			get: {
				tags: [ROOT_TAG],
				summary: "This SwaggerUI page",
				operationId: "viewSwaggerUI",
				parameters: [],
				security: [],
				responses: {
					"200": {
						description: "OpenAPI document",
						content: {
							"application/html": {
								schema: {
									type: "string",
								},
							},
						},
					},
				},
			},
		},
		[prefix + "-json"]: {
			get: {
				tags: [ROOT_TAG],
				summary: "The OpenAPI document in JSON",
				operationId: "getOpenAPIJSON",
				parameters: [],
				security: [],
				responses: {
					"200": {
						description: "OpenAPI document",
						content: {
							"application/json": {
								schema: {
									type: "string",
								},
							},
						},
					},
				},
			},
		},
		[prefix + "-yaml"]: {
			get: {
				tags: [ROOT_TAG],
				summary: "The OpenAPI document in YAML",
				operationId: "getOpenAPIYAML",
				parameters: [],
				security: [],
				responses: {
					"200": {
						description: "OpenAPI document",
						content: {
							"application/yaml": {
								schema: {
									type: "string",
								},
							},
						},
					},
				},
			},
		},
	};
	Object.assign(document.paths, paths);
}

const HTTP_METHODS = ["get", "post", "put", "patch", "delete", "options", "head"] as const;

/**
 * Clear the global security requirement on operations that are reachable without a session, so the
 * spec advertises them as public instead of falsely requiring the session cookie.
 *
 * An operation is public when it is served by a controller that is not behind {@link UserGuard} and
 * its Access Control permission admits an anonymous visitor (the `verejnost` role). Login endpoints
 * are the exception: they authenticate the request themselves rather than through the ACL link layer,
 * so they are not in the {@link RouteStore} and are opted out by operation id (see {@link LOGIN_OPERATION_IDS}).
 */
function markPublicOperations(document: OpenAPIObject) {
	const publicOperationIds = collectPublicAclOperationIds();

	for (const pathItem of Object.values(document.paths)) {
		for (const method of HTTP_METHODS) {
			const operation = pathItem[method];
			if (!operation) continue;

			const operationId = operation.operationId ?? "";
			if (publicOperationIds.has(operationId) || LOGIN_OPERATION_IDS.has(operationId)) {
				operation.security = [];
			}
		}
	}
}

/** Operation ids of ACL-linked routes that an anonymous visitor is allowed to reach. */
function collectPublicAclOperationIds(): Set<string> {
	const anonymousRequest = {} as Request;
	const publicOperationIds = new Set<string>();

	for (const route of RouteStore) {
		if (isBehindUserGuard(route.controller)) continue;

		// The permission may need a document for its check; anonymous public routes never do, and any
		// route that throws for a document-less check is treated as non-public (i.e. kept secured).
		let anonymousAllowed = false;
		try {
			anonymousAllowed = route.acl.can(anonymousRequest as never);
		} catch {
			anonymousAllowed = false;
		}

		if (anonymousAllowed) publicOperationIds.add(String(route.method));
	}

	return publicOperationIds;
}

/** Whether the controller owning a route is protected by {@link UserGuard} at the class level. */
function isBehindUserGuard(controllerPrototype: unknown): boolean {
	const controllerClass = (controllerPrototype as { constructor?: unknown })?.constructor;
	if (!controllerClass) return false;

	const guards: unknown[] = Reflect.getMetadata(GUARDS_METADATA, controllerClass) ?? [];
	return guards.some((guard) => guard === UserGuard || (guard as { constructor?: unknown })?.constructor === UserGuard);
}

/**
 * Login/logout endpoints authenticate the request themselves rather than through the ACL link layer,
 * so they are absent from the {@link RouteStore} and must be opted out of the session requirement by id.
 */
const LOGIN_OPERATION_IDS = new Set(["loginUsingCredentials", "loginUsingGoogle", "sendLoginLink", "loginUsingLink", "logout"]);
