name: Build Docker image

inputs:
  context:
    description: "Context for the Docker build"
    type: string
    required: true
  image-name:
    description: "Name of the Docker image"
    type: string
    required: true
  retention-days:
    description: "Number of days to retain the docker image"
    type: number
    default: 1
  build-args:
    description: "Build arguments"
    type: string
    required: false

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        tags: ${{ inputs.image-name }}:${{ github.sha }}
        outputs: type=docker
        cache-from: type=gha,scope=${{ inputs.image-name }}
        cache-to: type=gha,mode=max,scope=${{ inputs.image-name }}
        build-args: ${{ inputs.build-args }}

    - name: Save Docker image to tarball
      shell: bash
      run: docker save ${{ inputs.image-name }}:${{ github.sha }} -o ${{ inputs.image-name }}-docker-image.tar

    - name: Upload Docker image tarball
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.image-name }}-docker-image
        path: ${{ inputs.image-name }}-docker-image.tar
        retention-days: ${{ inputs.retention-days }}
