name: Resolve version

inputs:
  semver:
    description: "Version bump"
    required: true
    type: string
  prerelease:
    description: "Prerelease version"
    type: boolean
    required: false
    default: false

outputs:
  new_tag:
    description: "Resolved version tag"
    value: ${{ steps.version.outputs.new_tag }}

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: "0"

    - name: Resolve version tag
      id: version
      uses: anothrNick/github-tag-action@1.75.0
      env:
        TAG_PREFIX: v
        PRERELEASE: ${{ inputs.prerelease }}
        DEFAULT_BUMP: ${{ inputs.semver }}
        PRERELEASE_SUFFIX: next
        DRY_RUN: true
        FORCE_WITHOUT_CHANGES: true
        FORCE_WITHOUT_CHANGES_PRE: true
