/* tslint:disable */
/* eslint-disable */
/**
 * Bošán - Interní sekce
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-rc.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ConfigurationParameters {
	apiKey?: string | Promise<string> | ((name: string) => string) | ((name: string) => Promise<string>);
	username?: string;
	password?: string;
	accessToken?:
		| string
		| Promise<string>
		| ((name?: string, scopes?: string[]) => string)
		| ((name?: string, scopes?: string[]) => Promise<string>);
	basePath: string;
	serverIndex?: number;
	baseOptions?: any;
	formDataCtor?: new () => any;
	isJsonMime?: (mime: string) => boolean;
}

export const defaultConfigurationParameters: Partial<ConfigurationParameters> = {
	/**
	 * Check if the given MIME is a JSON MIME.
	 * JSON MIME examples:
	 *   application/json
	 *   application/json; charset=UTF8
	 *   APPLICATION/JSON
	 *   application/vnd.company+json
	 * @param mime - MIME (Multipurpose Internet Mail Extensions)
	 * @return True if the given MIME is JSON, false otherwise.
	 */
	isJsonMime: (mime: string) => {
		const jsonMime: RegExp = new RegExp("^(application\/json|[^;/ \t]+\/[^;/ \t]+[+]json)[ \t]*(;.*)?$", "i");
		return mime !== null && (jsonMime.test(mime) || mime.toLowerCase() === "application/json-patch+json");
	},
};
