name: Clean up untagged images

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cleanup:
    name: Delete untagged image versions
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete untagged APP image versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: interni-sekce
          package-type: container
          delete-only-untagged-versions: "true"
          min-versions-to-keep: 0

      - name: Delete untagged WORKER image versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: interni-sekce-worker
          package-type: container
          delete-only-untagged-versions: "true"
          min-versions-to-keep: 0
