name: Release to NEXT

on:
  workflow_dispatch:
  push:
    branches:
      - next

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # TODO:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Tests not implemented yet
  #       run: echo "No tests implemented yet"

  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_short_sha.outputs.short_sha }}
    steps:
      - name: Set short SHA
        id: set_short_sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  build:
    name: Build and publish
    needs: version
    uses: ./.github/workflows/build.yml
    with:
      context: .
      publish-image-name: bosancz/interni-sekce
      registry: ghcr.io
      tag: next
      build-args: |
        VERSION=NEXT-${{ needs.version.outputs.version }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      images: ${{ needs.build.outputs.images }}
    secrets: inherit

  tag:
    name: Tag release
    needs: deploy
    uses: ./.github/workflows/tag.yml
    with:
      tag: NEXT
